- name: Hello from Role
  ansible.builtin.debug:
    msg: Hello

- name: Print URL
  ansible.builtin.debug:
    msg: "{{URL}}"

- name: Copy file
  ansible.builtin.copy:
    src: Sample.tx t
    dest: /tmp/sample-file.txt

- name: Template a file
  ansible.builtin.template:
    src: Sample.txt
    dest: /tmp/sample-template.txt