- name: demo on loops
  hosts: localhost
  tasks:
    - name: loop example
      debug:
        msg: fruit = {{item}}
      loop:
        - apple
        - banana
## it is going to print the output for both apple and banana iteration comes into picture here###

###when we multiple values to a loop(map)###
- name: loop example with maps
  debug:
    msg: fruit Name = {{item.name}}, quantity = {{item.quantity}}
  loop:
    - {name:apple, quantity: 10}
    - {name: banana, quantity: 30}
