- name: play level vars
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL= {{ URL }}

- name: vars from files
  hosts: localhost
  vars_files:
    - demo-vars.yml
  tasks:
    - name: print url
      ansible.builtin.debug:
        msg: URL = {{ URL }}
